routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes(['register' => false]);

Route::group(['prefix' => 'company', 'as' => 'company.',  'middleware' => ['auth','valid_user']], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'App\Http\Controllers\Company\CompanyController@index']);
    Route::post('/', ['as' => 'store', 'uses' => 'App\Http\Controllers\Company\CompanyController@store']);
    Route::put('/', ['as' => 'update', 'uses' => 'App\Http\Controllers\Company\CompanyController@update']);
    Route::delete('/{id}', ['as' => 'delete', 'uses' => 'App\Http\Controllers\Company\CompanyController@destroy']);
    Route::get('/api', ['as' => 'api.index', 'uses' => 'App\Http\Controllers\Company\CompanyAPIController@index']);
    Route::get('/api/list', ['as' => 'api.list', 'uses' => 'App\Http\Controllers\Company\CompanyAPIController@list']);
});

Route::group(['prefix' => 'employee', 'as' => 'employee.', 'middleware' => ['auth','valid_user']], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'App\Http\Controllers\Employee\EmployeeController@index']);
    Route::post('/', ['as' => 'store', 'uses' => 'App\Http\Controllers\Employee\EmployeeController@store']);
    Route::put('/', ['as' => 'update', 'uses' => 'App\Http\Controllers\Employee\EmployeeController@update']);
    Route::delete('/{id}', ['as' => 'delete', 'uses' => 'App\Http\Controllers\Employee\EmployeeController@destroy']);
    Route::get('/api', ['as' => 'api.index', 'uses' => 'App\Http\Controllers\Employee\EmployeeAPIController@index']);
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ config('app.name') }}</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
          integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
          crossorigin="anonymous"/>

    <link href="{{ mix('css/app.css') }}" rel="stylesheet">

    @yield('third_party_stylesheets')

    @stack('page_css')
</head>

<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
    <!-- Main Header -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown user-menu">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                    <img src="https://laravel.com/img/logomark.min.svg"
                         class="user-image img-circle elevation-2" alt="User Image">
                    <span class="d-none d-md-inline">{{ Auth::user()->name }}</span>
                </a>
                <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <!-- User image -->
                    <li class="user-header bg-primary">
                        <img src="https://laravel.com/img/logomark.min.svg"
                             class="img-circle elevation-2"
                             alt="User Image">
                        <p>
                            {{ Auth::user()->name }}
                            <small>Member since {{ Auth::user()->created_at->format('M. Y') }}</small>
                        </p>
                    </li>
                    <!-- Menu Footer-->
                    <li class="user-footer">
                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                        <a href="#" class="btn btn-default btn-flat float-right"
                           onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            Sign out
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
                        </form>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>

    <!-- Left side column. contains the logo and sidebar -->
@include('layouts.sidebar')

<!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <section class="content">
            @yield('content')
        </section>
    </div>

    <!-- Main Footer -->
    <footer class="main-footer">
        <div class="float-right d-none d-sm-block">
            <b>Version</b> 3.0.5
        </div>
        <strong>Copyright &copy; 2014-2020 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights
        reserved.
    </footer>
</div>



@yield('third_party_scripts')

@stack('page_scripts')
</body>
</html>

resources/views/layouts/menu.blade.php
<!-- need to remove -->
<li class="nav-item">
    <a href="{{ route('company.index') }}" class="nav-link {{ (request()->is('company')) ? 'active' : '' }}">
        <i class="nav-icon fas fa-briefcase"></i>
        <p>Companies</p>
    </a>
    <a href="{{ route('employee.index') }}" class="nav-link {{ (request()->is('employee')) ? 'active' : '' }}" >
        <i class="nav-icon fas fa-user"></i>
        <p>Employees</p>
    </a>
</li>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="{{ route('home') }}" class="brand-link">
        <img src="https://laravel.com/img/logomark.min.svg"
             alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3">
        <span class="brand-text font-weight-light">{{ config('app.name') }}</span>
    </a>

    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                @include('layouts.menu')
            </ul>
        </nav>
    </div>

</aside>